[package]
name = "kirisaku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspirv = "0.11.0+1.5.4"
spirv = "0.2.0+1.5.4"

rustc-hash = "1.1.0"
indexmap = "2.1.0"